#!/usr/bin/env python
"""Freeze the raw data on a stated date: copy the manifest to data/raw/manifest_frozen_<date>.csv, and write docs/DATA_FREEZE.md with
the counts, bytes, latest access dates by group, the SHA-256 of the frozen manifest and the freeze rule. Run after the last fetch
that feeds the report; files fetched later stay in the store but do not enter the frozen manifest."""
from __future__ import annotations

import argparse
import hashlib
import shutil
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
import pandas as pd  # noqa: E402

from src.paths import MANIFEST, PROCESSED, RAW, ROOT  # noqa: E402


def main() -> int:
    ap = argparse.ArgumentParser(); ap.add_argument("--date", required=True); a = ap.parse_args()
    m = pd.read_csv(MANIFEST)
    m = m[m.access_date <= a.date]
    frozen = RAW / f"manifest_frozen_{a.date}.csv"; m.to_csv(frozen, index=False)
    sha = hashlib.sha256(frozen.read_bytes()).hexdigest()
    latest = m.sort_values("access_date").groupby("source_id").tail(1)
    missing = [p for p in latest.local_path if not (ROOT / p).exists()]
    by_group = latest.groupby("group").agg(files=("source_id", "size"), bytes=("bytes", "sum"), latest_access=("access_date", "max")).reset_index()
    try:
        commit = subprocess.run(["git", "rev-parse", "--short", "HEAD"], cwd=ROOT, capture_output=True, text=True).stdout.strip()
    except Exception:
        commit = "n/a"
    proc = sorted(PROCESSED.glob("ch*_*")) + sorted(PROCESSED.glob("*.parquet"))
    lines = [f"# Data freeze: {a.date}", "",
             f"All figures, tables and numbers in the report are built from raw files recorded in `data/raw/manifest_frozen_{a.date}.csv` "
             f"(SHA-256 `{sha}`), a copy of `data/raw/manifest.csv` restricted to access dates on or before {a.date}. It holds {len(m)} rows for "
             f"{latest.source_id.nunique()} source ids ({latest.bytes.sum()/1e9:.2f} GB); where a source was fetched more than once the pipeline uses "
             f"the latest access date, as `src.ch1_baseline.manifest()` does. {len(missing)} of the {len(latest)} referenced files are missing from the local store.",
             "", "**Rule.** Nothing fetched after the freeze date enters the report. The monthly snapshot job (`scripts/snapshot.py`) keeps adding "
             "ERCOT, CEC docket, PJM, Epoch and EIA-860M vintages under `data/snapshots/` and `data/raw/` for the longitudinal dataset, but a later "
             "vintage is used only in a new, dated freeze. The repository commit that carries this freeze is tagged `data-freeze-" + a.date + "` "
             f"(prepared at commit `{commit}`).", "",
             "**What the freeze covers, by group (latest access date per source id):**", "",
             "| Group | Source ids | Bytes | Latest access |", "|---|---:|---:|---|"]
    for r in by_group.sort_values("group").itertuples():
        lines.append(f"| {r.group} | {r.files} | {r.bytes/1e6:,.1f} MB | {r.latest_access} |")
    lines += ["", f"**Processed outputs at the freeze:** {len(proc)} files under `data/processed/` (chapter outputs `ch1_*` to `ch4_*` and the hourly parquet caches), "
              "regenerated by `make ch1`, `make ch2`, `make ch3`, `make ch4` and `make provenance`; exported with the report by `make release`.", "",
              "**Sources read only in a browser (not fetchable by the pipeline):** the FERC docket page for RM26-4 (HTTP 403 to non-browser clients; its facts are "
              "carried by the CAISO and NERC filings and the two FERC news pages in the store). Chart values transcribed from PDF page images (ERCOT decks and "
              "overviews, PJM LAS summary) are listed with their manifest ids in `src/ch4_gap.py` and `src/ch4_regimes.py`.", ""]
    (ROOT / "docs" / "DATA_FREEZE.md").write_text("\n".join(lines))
    print(f"frozen manifest {frozen.name}: {len(m)} rows, {latest.source_id.nunique()} ids, sha256 {sha[:12]}; missing files {len(missing)}; docs/DATA_FREEZE.md written")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
